# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "Checkmarx"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1      
      - name: Build
        run: echo "build"
      - name: Checkmarx Action
        uses: checkmarx-ts/checkmarx-github-action@<version>
        with:
          cxServer: https://ast.checkmarx.net/
          cxApiToken: ${{ secrets.CF_TOKEN }}
          cxTeam: devtst_poc
      - name: Complete
        run: echo "Complete"
