# This is a basic workflow to help you get started with Actions

name: VeraCode Scan and Upload

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command          
      - run: |
          zip -r scan.zip .
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.4
        with: 
          appname: Juice Shop
          vid: ${{ secrets.VERACODE_ID }}
          vkey: ${{ secrets.VERACODE_SECRET }}
          filepath: scan.zip
      - uses: actions/upload-artifact@v3
        with:
          name: veracode_upload
          path: scan.zip      